-- Generated from data/drops.json. Review before running in Supabase SQL Editor.
-- Generated at 2026-07-06T08:12:44.726Z.

alter table public.drops add column if not exists method text not null default 'official';
alter table public.drops add column if not exists status_ja text;
alter table public.drops add column if not exists status_en text;
alter table public.drops add column if not exists source_label text;
alter table public.drops add column if not exists icon text;
alter table public.drops add column if not exists art_a text;
alter table public.drops add column if not exists art_b text;

insert into public.drops (
  id,
  title_ja,
  title_en,
  brand,
  category,
  method,
  state,
  status_ja,
  status_en,
  official_url,
  source_label,
  release_at,
  deadline_at,
  area_ja,
  area_en,
  purchase_limit_ja,
  purchase_limit_en,
  how_ja,
  how_en,
  tags,
  icon,
  art_a,
  art_b,
  published_at
)
values
(
    'holo-yoshinoya',
    '吉野家 アニメ/ホロライブ系コラボキャンペーン監視',
    'Yoshinoya anime and Hololive-style collab campaign watch',
    'ホロライブ',
    '飲食コラボ',
    '店頭',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.yoshinoya.com/',
    '吉野家公式（監視対象）',
    null,
    null,
    '全国の対象店舗',
    'Participating stores in Japan',
    '未確認。配布条件・数量・対象店舗は公式ページで確認',
    'Unconfirmed. Check official pages for bonus rules, quantity, and stores',
    '公式キャンペーンページで作品名、開催期間、対象店舗、配布条件が確認できたものだけ公開カード化。',
    'Publish only after official pages confirm title, period, stores, and bonus rules.',
    array['ホロライブ', '飲食コラボ', '外食', '店頭', '数量限定', '公式確認', '未確認']::text[],
    'i-ticket',
    '#e85c4f',
    '#f6d37a',
    now()
  ),
(
    'sukiya-collab-watch',
    'すき家 アニメ/ゲーム コラボキャンペーン監視',
    'Sukiya anime and game collab campaign watch',
    'すき家',
    '飲食コラボ',
    '店頭',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.sukiya.jp/',
    'すき家公式（監視対象）',
    null,
    null,
    '全国のすき家対象店舗',
    'Participating Sukiya stores in Japan',
    '未確認。対象メニュー、配布条件、早期終了、店舗差を確認',
    'Unconfirmed. Check eligible menu, bonus conditions, early end, and store differences',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['すき家', '飲食コラボ', '外食', '店頭', '数量限定', '公式確認', '未確認']::text[],
    'i-ticket',
    '#e84b3c',
    '#f5c84b',
    now()
  ),
(
    'cocoichi-collab-watch',
    'CoCo壱番屋 コラボメニュー/特典キャンペーン監視',
    'CoCo Ichibanya collab menu and bonus campaign watch',
    'ココイチ',
    '飲食コラボ',
    '店頭/予約',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.ichibanya.co.jp/',
    'CoCo壱番屋公式（監視対象）',
    null,
    null,
    'CoCo壱番屋 対象店舗/通販',
    'Participating CoCo Ichibanya stores and online',
    '未確認。コラボメニュー、店頭配布、通販グッズ、対象店舗を確認',
    'Unconfirmed. Check collab menu, in-store bonuses, online goods, and participating stores',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ココイチ', '飲食コラボ', '外食', '店頭', '通販', '公式確認', '未確認']::text[],
    'i-ticket',
    '#f1b53a',
    '#5a3624',
    now()
  ),
(
    'gusto-skylark-collab-watch',
    'ガスト/すかいらーく系 コラボメニュー・限定グッズ監視',
    'Gusto and Skylark collab menu and limited goods watch',
    'ガスト',
    '飲食コラボ',
    '店頭/予約',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.skylark.co.jp/',
    'すかいらーく公式（監視対象）',
    null,
    null,
    'ガスト・すかいらーくグループ対象店舗',
    'Participating Gusto and Skylark Group stores',
    '未確認。対象ブランド、配布条件、対象店舗、売り切れを確認',
    'Unconfirmed. Check target brands, bonus conditions, stores, and sellout status',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ガスト', 'すかいらーく', '飲食コラボ', '外食', '店頭', '公式確認', '未確認']::text[],
    'i-ticket',
    '#f08b3c',
    '#2f7dc3',
    now()
  ),
(
    'mcdonalds-happyset-watch',
    'マクドナルド ハッピーセット/ポケモンコラボ監視',
    'McDonald''s Happy Meal and Pokemon collab watch',
    'マクドナルド',
    '飲食コラボ',
    '店頭',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.mcdonalds.co.jp/family/happyset/',
    'マクドナルド公式（監視対象）',
    null,
    null,
    '全国のマクドナルド対象店舗',
    'Participating McDonald''s stores in Japan',
    '未確認。販売期間、週替わりおもちゃ、早期終了、購入制限を確認',
    'Unconfirmed. Check sales period, weekly toys, early sellout, and purchase limits',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['マクドナルド', 'ポケモン', 'ハッピーセット', '飲食コラボ', '外食', '店頭', '数量限定', '公式確認', '未確認']::text[],
    'i-ticket',
    '#f5c542',
    '#d61f2c',
    now()
  ),
(
    'pokemon-card-30th',
    'ポケモンカード 新商品・抽選情報ウォッチ',
    'Pokemon Card new products and lottery watch',
    'ポケモン',
    'カード',
    '公式確認',
    'soon',
    '告知監視',
    'Notice watch',
    'https://www.pokemon-card.com/products/',
    'ポケカ公式（監視対象）',
    null,
    null,
    '公式商品・ニュースページ',
    'Official product and news pages',
    '未確認。商品個別ページで発売日・抽選締切・購入条件を確認',
    'Unconfirmed. Check product pages for release date, lottery due date, and purchase rules',
    '公式商品ページ/ニュースで商品個別URL、発売日、抽選締切が確認できたものだけ公開カード化。',
    'Publish only after an official product/news URL confirms release date and lottery deadline.',
    array['ポケカ', '抽選', 'オンライン', '購入条件', '公式確認', '未確認']::text[],
    'i-card',
    '#f2cf48',
    '#4ba3d9',
    now()
  ),
(
    'gunpla-limited',
    'HG ガンプラ新作・限定再販チェック',
    'HG Gunpla new and limited restock watch',
    'ガンダム',
    'プラモデル',
    '店頭/通販',
    'soon',
    '告知監視',
    'Notice watch',
    'https://www.bandaispirits.co.jp/',
    'バンダイホビー公式（監視対象）',
    null,
    null,
    '量販店・模型店・プレバン',
    'Retailers, hobby shops, Premium Bandai',
    '未確認。店舗により1人1点などの制限あり',
    'Unconfirmed. Purchase limits vary by store',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ガンプラ', '再販', '店頭', '購入制限', '公式確認', '未確認']::text[],
    'i-box',
    '#e6edf4',
    '#2f7dc3',
    now()
  ),
(
    'ichiban-kuji-holo',
    '一番くじ アニメ/ホロライブ系ラインナップ監視',
    'Ichiban Kuji anime and Hololive-style lineup watch',
    'ホロライブ',
    '一番くじ',
    '店頭/オンライン',
    'store',
    '告知監視',
    'Notice watch',
    'https://1kuji.com/',
    '一番くじ公式（監視対象）',
    null,
    null,
    'コンビニ・書店・ホビー店',
    'Convenience stores, bookstores, hobby shops',
    '未確認。ロットや購入回数制限は店舗ごと',
    'Unconfirmed. Per-person limits vary by location',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ホロライブ', '一番くじ', 'コンビニ', '店頭', '公式確認', '未確認']::text[],
    'i-ticket',
    '#7bded2',
    '#7b68d6',
    now()
  ),
(
    'banpresto-prize',
    'クレーンゲーム新作フィギュア 登場スケジュール',
    'Arcade prize figure release schedule',
    'バンプレスト',
    'プライズ',
    '店頭',
    'store',
    '告知監視',
    'Notice watch',
    'https://bsp-prize.jp/',
    'バンプレストナビ（監視対象）',
    null,
    null,
    'ゲームセンター',
    'Arcades',
    '未確認。在庫・投入日は店舗差あり',
    'Unconfirmed. Arrival date and stock differ by arcade',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['プライズ', 'フィギュア', '店頭', '店舗検索', '公式確認', '未確認']::text[],
    'i-box',
    '#f7b0c8',
    '#7ad0ff',
    now()
  ),
(
    'dragonball-figure-watch',
    'ドラゴンボール新作フィギュア・一番くじ横断チェック',
    'Dragon Ball figure and Ichiban Kuji watch',
    'ドラゴンボール',
    'フィギュア/くじ',
    '店頭/オンライン',
    'store',
    '告知監視',
    'Notice watch',
    'https://dragon-ball-official.com/',
    'ドラゴンボール公式/バンダイ系（監視対象）',
    null,
    null,
    'ゲームセンター・コンビニ・ホビー店',
    'Arcades, convenience stores, hobby shops',
    '未確認。購入回数・投入日・入荷数は店舗差あり',
    'Unconfirmed. Play limits, arrival date, and stock vary by store',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ドラゴンボール', 'フィギュア', '一番くじ', '店頭', '公式確認', '未確認']::text[],
    'i-box',
    '#ff9f1a',
    '#2478b8',
    now()
  ),
(
    'initiald-popup-goods',
    '頭文字D POP UP STORE グッズ・物販イベント',
    'Initial D pop-up store goods event',
    '頭文字D',
    'イベント/グッズ',
    '店頭/オンライン',
    'store',
    '告知監視',
    'Notice watch',
    'https://initiald-portal.com/',
    '頭文字D公式/会場告知（監視対象）',
    null,
    null,
    '都内・対象ショップ/通販',
    'Tokyo shops and online store',
    '未確認。整理券・購入制限・事後通販の有無を確認',
    'Unconfirmed. Check entry tickets, purchase limits, and online after-sale',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['頭文字D', 'イベント', 'グッズ', '店頭', '公式確認', '未確認']::text[],
    'i-ticket',
    '#f3b340',
    '#1f2930',
    now()
  ),
(
    'initiald-haruna-event',
    '頭文字D 榛名・伊香保エリア聖地イベント候補',
    'Initial D Haruna and Ikaho event watch',
    '頭文字D',
    '聖地イベント',
    '現地',
    'soon',
    '告知監視',
    'Notice watch',
    'https://initiald-portal.com/',
    '公式/観光・会場告知（監視対象）',
    null,
    null,
    '群馬・渋川/伊香保/榛名方面',
    'Shibukawa, Ikaho, and Haruna area',
    '未確認。開催日・交通手段・宿泊空きに注意',
    'Unconfirmed. Check dates, transport, and hotel availability',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['頭文字D', 'イベント', '聖地', '遠征', '公式確認', '未確認']::text[],
    'i-route',
    '#2f7dc3',
    '#f3b340',
    now()
  ),
(
    'frieren-exhibition-goods',
    '葬送のフリーレン 展示・グッズイベント候補',
    'Frieren exhibition and goods event watch',
    'フリーレン',
    '展示/グッズ',
    '店頭/オンライン',
    'store',
    '告知監視',
    'Notice watch',
    'https://frieren-anime.jp/',
    '作品公式/会場告知（監視対象）',
    null,
    null,
    '都内会場・アニメショップ',
    'Tokyo venue and anime shops',
    '未確認。入場整理券・限定グッズ・事後通販を確認',
    'Unconfirmed. Check entry tickets, limited goods, and online after-sale',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['フリーレン', '海外人気', '女性人気', 'イベント', '公式確認', '未確認']::text[],
    'i-star',
    '#b7d8c5',
    '#6f86bc',
    now()
  ),
(
    'chiikawa-popup-goods',
    'ちいかわ POP UP・新作雑貨チェック',
    'Chiikawa pop-up and new goods watch',
    'ちいかわ',
    'キャラ雑貨',
    '店頭/オンライン',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.chiikawa-info.jp/',
    'ちいかわ公式/ショップ告知（監視対象）',
    null,
    null,
    'キャラショップ・駅ナカ・通販',
    'Character shops, station stores, and online',
    '未確認。整理券・購入制限・在庫切れに注意',
    'Unconfirmed. Watch for entry tickets, purchase limits, and sellouts',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ちいかわ', '女性人気', 'グッズ', '休憩向け', '公式確認', '未確認']::text[],
    'i-star',
    '#ffd4e2',
    '#f7df7e',
    now()
  ),
(
    'ghibli-ticket-watch',
    'ジブリ美術館・ジブリ関連チケット確認',
    'Ghibli museum and related ticket watch',
    'ジブリ',
    '観光/チケット',
    '予約',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.ghibli-museum.jp/',
    '公式予約/観光告知（監視対象）',
    null,
    null,
    '三鷹・公式予約',
    'Mitaka and official reservation',
    '未確認。日時指定・売り切れが早い。観光寄りの日に向く',
    'Unconfirmed. Timed tickets can sell out quickly. Good for a sightseeing-leaning day.',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ジブリ', '海外人気', '女性人気', '観光', '公式確認', '未確認']::text[],
    'i-ticket',
    '#7db28f',
    '#f3b340',
    now()
  ),
(
    'sanrio-cafe-goods',
    'サンリオ カフェ・限定雑貨・キャラショップ',
    'Sanrio cafe, limited goods, and character shops',
    'サンリオ',
    'カフェ/雑貨',
    '店頭/予約',
    'store',
    '告知監視',
    'Notice watch',
    'https://www.sanrio.co.jp/',
    'サンリオ公式/店舗告知（監視対象）',
    null,
    null,
    '原宿・新宿・キャラショップ',
    'Harajuku, Shinjuku, and character shops',
    '未確認。カフェ予約・限定ノベルティ・整理券を確認',
    'Unconfirmed. Check cafe booking, limited bonuses, and entry tickets',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['サンリオ', '女性人気', '海外人気', '観光向け', '公式確認', '未確認']::text[],
    'i-ticket',
    '#f8b7cc',
    '#87c7f2',
    now()
  ),
(
    'gasha-dragonquest',
    'ドラゴンクエスト系 カプセルトイ新作監視',
    'Dragon Quest-style capsule toy release watch',
    'ドラクエ',
    'ガチャ',
    '店頭',
    'soon',
    '告知監視',
    'Notice watch',
    'https://www.gashapon.jp/',
    'ガシャポン公式（監視対象）',
    null,
    null,
    'カプセル自販機・専門店',
    'Capsule machines and specialty stores',
    '未確認。発売時期は地域・店舗で差あり',
    'Unconfirmed. Release timing differs by region and store',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ドラクエ', 'ガチャ', '店頭', '発売週', '公式確認', '未確認']::text[],
    'i-capsule',
    '#72c16f',
    '#f5d45d',
    now()
  ),
(
    'goodsmile-holo',
    'ホロライブ系 フィギュア出荷予定監視',
    'Hololive-style figure shipping watch',
    'ホロライブ',
    'フィギュア',
    '通販',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.goodsmile.com/ja/releaseinfo',
    'グッドスマイル公式（監視対象）',
    null,
    null,
    '通販・ホビーショップ',
    'Online and hobby shops',
    '未確認。流通限定・再販表記に注意',
    'Unconfirmed. Watch for limited distribution or rerelease labels',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['ホロライブ', 'フィギュア', '通販', '再販', '公式確認', '未確認']::text[],
    'i-box',
    '#66c9e8',
    '#e8e0ff',
    now()
  ),
(
    'frieren-comic-volume',
    '葬送のフリーレン 最新刊・特装版チェック',
    'Frieren latest volume and special edition watch',
    'フリーレン',
    '単行本',
    '店頭/通販',
    'soon',
    '告知監視',
    'Notice watch',
    'https://frieren-anime.jp/',
    '出版社/作品公式（監視対象）',
    null,
    null,
    '書店・電子書籍・通販',
    'Bookstores, ebook stores, and online',
    '未確認。特装版・初回特典・店舗別特典を確認',
    'Unconfirmed. Check special editions, first-run bonuses, and store bonuses',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['フリーレン', '新刊', '単行本', '原作', '公式確認', '未確認']::text[],
    'i-book',
    '#d8e7d7',
    '#7b8fc7',
    now()
  ),
(
    'jump-comics-new-release',
    'ジャンプ系コミックス新刊・関連書籍チェック',
    'Jump comics new volume and related book watch',
    'ジャンプ',
    '新刊',
    '店頭/通販',
    'soon',
    '告知監視',
    'Notice watch',
    'https://www.shonenjump.com/',
    '出版社公式/書店告知（監視対象）',
    null,
    null,
    '書店・電子書籍・通販',
    'Bookstores, ebook stores, and online',
    '未確認。店舗特典・同日発売グッズ・電子版の有無を確認',
    'Unconfirmed. Check store bonuses, same-day goods, and ebook availability',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['新刊', '単行本', '原作', 'ドラゴンボール', '公式確認', '未確認']::text[],
    'i-book',
    '#f7d44c',
    '#e24d3f',
    now()
  ),
(
    'author-new-work-watch',
    '推し作者の新連載・読み切り・新作発表ウォッチ',
    'Favorite creator new series and one-shot watch',
    '推し作者',
    '作者新作',
    '公式告知',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.shueisha.co.jp/',
    '出版社/作者公式（監視対象）',
    null,
    null,
    '出版社サイト・雑誌・公式SNS',
    'Publisher sites, magazines, and official social channels',
    '未確認。雑誌掲載、電子配信、単行本化予定は別々に確認',
    'Unconfirmed. Magazine run, digital release, and future volume plans can differ',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['作者新作', '新連載', '読み切り', '原作', '公式確認', '未確認']::text[],
    'i-book',
    '#f3f0d9',
    '#0c8f7a',
    now()
  ),
(
    'anime-adaptation-watch',
    '原作アニメ化・続編・映画化 発表ウォッチ',
    'Manga anime adaptation, sequel, and movie announcement watch',
    '原作ニュース',
    'アニメ化',
    '公式告知',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.animatetimes.com/',
    '作品公式/アニメ公式（監視対象）',
    null,
    null,
    '作品公式・出版社・アニメ公式・PV',
    'Series site, publisher, anime site, and trailers',
    '未確認。ティザー、放送時期、制作会社、原作巻数、先行上映を確認',
    'Unconfirmed. Check teaser, release window, studio, source volumes, and advance screenings',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['アニメ化', '原作', 'イベント', '海外人気', '公式確認', '未確認']::text[],
    'i-ticket',
    '#8cc8ff',
    '#6d5bd0',
    now()
  ),
(
    'artist-related-works',
    '作画担当の関連作品・画集・新作イラストチェック',
    'Artist related works, artbook, and new illustration watch',
    '作画担当',
    '作画/画集',
    '公式告知',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.shueisha.co.jp/',
    '出版社/作家公式（監視対象）',
    null,
    null,
    '出版社・画集・展覧会・公式SNS',
    'Publisher, artbooks, exhibitions, and official social channels',
    '未確認。原作担当と作画担当を分け、別作品・画集・展示を確認',
    'Unconfirmed. Track writer and artist separately; check other works, artbooks, and exhibitions',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['作画', '画集', '関連作品', '原作', '公式確認', '未確認']::text[],
    'i-book',
    '#f7c6a3',
    '#6d5bd0',
    now()
  ),
(
    'writer-artist-credit-watch',
    '原作・作画・キャラデザ別名義/関連作品ウォッチ',
    'Writer, artist, and character designer credit watch',
    '原作/作画',
    '関連作品',
    '公式告知',
    'online',
    '告知監視',
    'Notice watch',
    'https://www.animatetimes.com/',
    '作品公式/スタッフ告知（監視対象）',
    null,
    null,
    '作品公式・出版社・スタッフ告知',
    'Series sites, publishers, and staff notices',
    '未確認。原作/作画/キャラデザ/イラスト担当を別軸で登録',
    'Unconfirmed. Track writer, artist, character designer, and illustrator as separate axes',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['原作', '作画', '関連作品', '作者新作', '公式確認', '未確認']::text[],
    'i-star',
    '#b7d8c5',
    '#e24d3f',
    now()
  ),
(
    'bandai-candy',
    'キャラ食玩・ウエハース発売カレンダー',
    'Character candy and wafer release calendar',
    'バンダイ',
    '食玩',
    '店頭',
    'soon',
    '告知監視',
    'Notice watch',
    'https://www.bandai.co.jp/candy/',
    'バンダイキャンディ公式（監視対象）',
    null,
    null,
    'スーパー・コンビニ・量販店',
    'Supermarkets, convenience stores, retailers',
    '未確認。売場・入荷日は店舗差あり',
    'Unconfirmed. Shelf timing differs by store',
    '公式ページで商品個別URL、発売日/開始日、締切、購入条件が確認できたものだけ公開カード化。',
    'Publish only after an official page confirms the item URL, date, deadline, and purchase rules.',
    array['食玩', 'ポケモン', 'ちいかわ', '店頭', '公式確認', '未確認']::text[],
    'i-box',
    '#fdcf6f',
    '#ff8f8f',
    now()
  )
on conflict (id) do update set
  title_ja = excluded.title_ja,
  title_en = excluded.title_en,
  brand = excluded.brand,
  category = excluded.category,
  method = excluded.method,
  state = excluded.state,
  status_ja = excluded.status_ja,
  status_en = excluded.status_en,
  official_url = excluded.official_url,
  source_label = excluded.source_label,
  release_at = excluded.release_at,
  deadline_at = excluded.deadline_at,
  area_ja = excluded.area_ja,
  area_en = excluded.area_en,
  purchase_limit_ja = excluded.purchase_limit_ja,
  purchase_limit_en = excluded.purchase_limit_en,
  how_ja = excluded.how_ja,
  how_en = excluded.how_en,
  tags = excluded.tags,
  icon = excluded.icon,
  art_a = excluded.art_a,
  art_b = excluded.art_b,
  published_at = coalesce(public.drops.published_at, excluded.published_at),
  updated_at = now();
